### ISSUE TITLE
部门分页查询异常

### ISSUE THREAD

**Issue by Dev-Flo200** [shiwei-Ren/smpe-admin#26]
### 

### 错误信息
文件位置：
**smpe-admin/smpe-system/src/main/java/marchsoft/modules/system/controller/DeptController.java /**
```java
   @ApiOperation("查询部门")
    @GetMapping
    @PreAuthorize("@smpe.check('user:list','dept:list')")
    public Result<Object> query(DeptQueryCriteria criteria, PageVO pageVO) {
        log.info("【查询部门 /api/dept】操作人userId:" + SecurityUtils.getCurrentUserId() + "; 部门查询条件 criteria= " + criteria + "; 分页pageVo= " + pageVO);
        pageVO.setSize(-1);  //此处代码限制了分页查询
        return Result.success(deptService.queryAll(criteria, pageVO, true));
    }
```

**Comment by pangyv** [comment]
![image](https://user-images.githubusercontent.com/53242048/101984242-08da3080-3cbb-11eb-818b-227422663eea.png)
这个部门查询接口与[配套web页面](https://github.com/shiwei-Ren/smpe-admin-web)经过协商，从而定义为不分页的查询。因为图中红圈功能（点开三角，查询子部门）的接口也是调用此接口，如果加上分页查询，会导致子部门超出分页个数从而显示不全的情况。
