### ISSUE TITLE
修改菜单组件名称不生效

### ISSUE THREAD

**Issue by NancyDancy** [shiwei-Ren/smpe-admin#30]
### 当前使用版本(必填,否则不予处理)

v0.1.0-beta

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据库组件名称字段为name
前端传参组件名称：componentName，后端数据库Menu实体未做映射

**Comment by shiwei-Ren** [comment]
#### 解决
统一使用name

`marchsoft.modules.system.entity.dto.MenuDTO`的`componentName`修改为`name`

前端组件传值name
