### ISSUE TITLE
个人中心修改信息之后显示的还是修改之前的

### ISSUE THREAD

**Issue by NancyDancy** [shiwei-Ren/smpe-admin#33]
### 当前使用版本(必填,否则不予处理)

v0.1.0-beta

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

修改用户信息之后未清除缓存，查询的还是缓存里的信息

usercontroller里直接调用mybatis的修改方法，修改之后并未清除用户缓存

**Comment by shiwei-Ren** [comment]
#### 解决
在`UserController`的接口方法中，添加如下方法即可解决
`userCacheClean.cleanUserCache(SecurityUtils.getCurrentUserId());`
