### ISSUE TITLE
update语句更新返回值建议

### ISSUE THREAD

**Issue by Dev-Flo200** [shiwei-Ren/smpe-admin#35]
### 建议内容
update类的语句执行后返回数据影响数而不是匹配数

### 实施方案
在jdbc的url后拼接useAffectedRows=true

**Comment by Dev-Flo200** [comment]
update返回影响数后，菜单修改名字，会更新父级菜单的子菜单数，因为只变了名字因此，父级菜单的子菜单数不变，更新会返回false,请注意！！

**Comment by shiwei-Ren** [comment]
通用框架我们尽量做的是通用处理，我们默认数据库的增删改还是使用受影响行数。主要考虑到的是如果改为受影响行数，那么数据库位置异常和数据为变动行数都是0，不好做区分。我们通过这个行数做异常处理，所以暂时使用匹配行数。

如果又需要可自行更改为`useAffectedRows=true`，设置为受影响行数。
