### ISSUE TITLE
菜单显示和角色查看菜单权限问题

### ISSUE THREAD

**Issue by xuyunfeiQQ** [shiwei-Ren/smpe-admin#41]
### 当前使用版本(必填,否则不予处理)
v0.1.2-dev

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
前端显示与数据库中的记录不同步

### 重现步骤(如果有就写完整)
在前端更改角色对菜单的权限后，数据库相应记录发生变化，但是前端在刷新后仍旧没有改变（包括左侧菜单及菜单子目录）

**Comment by shiwei-Ren** [comment]
mybatis二级缓存的问题，在application.yml文件中关闭二级缓存即可。
新的缓存方案会在下一版本推出
