### ISSUE TITLE
角色的菜单显示与后端数据库中的记录不同步

### ISSUE THREAD

**Issue by xuyunfeiQQ** [shiwei-Ren/smpe-admin#42]
### 当前使用版本(必填,否则不予处理)
v0.1.2-dev

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
前端的角色对于菜单的权限与数据库中的记录不同步

### 重现步骤(如果有就写完整)
更改角色对于菜单的权限并保存 => 查看数据库，对应记录发生改变 => 刷新前端页面，仍为更改前的菜单显示

### 报错信息
无

**Comment by shiwei-Ren** [comment]
mybatis二级缓存的问题，在application.yml文件中关闭二级缓存即可。
新的缓存方案会在下一版本推出

**Comment by shiwei-Ren** [comment]
已经使用全新的缓存方案，此问题已经解决
